apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-frontend
  namespace: frontend       # <-- specify your namespace here
  labels:
    app: ecommerce-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-frontend
  template:
    metadata:
      labels:
        app: ecommerce-frontend
    spec:
      containers:
        - name: ecommerce-frontend
          image: ecommerce-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
